---
extends: default
rules:
  indentation:
    level: error
  comments-indentation: disable
  document-start:
    level: error
  truthy:
    level: error
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
    check-keys: true
  braces:
    level: error
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 1
  comments:
    level: error
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  line-length:
    level: error
    max: 90
    allow-non-breakable-inline-mappings: true
  octal-values:
    level: error
    forbid-implicit-octal: true
    forbid-explicit-octal: true
