# kics-scan disable=555ab8f9-2001-455e-a077-f2d0f41e2fb9
---
name: build and push
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "11 11 * * 1"
jobs:
  define-matrix:
    name: define matrix
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.define-matrix.outputs.images }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: define matrix
        id: define-matrix
        run: |
          source ./matrix.sh
          echo "images=${DIR_SON}" >> "${GITHUB_OUTPUT}"
  build-n-push:
    name: "build ${{ matrix.image }} image"
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJSON(needs.define-matrix.outputs.images) }}
    timeout-minutes: 22
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: build and test images
        run: |
          sudo ./podman.sh
          MANUAL_IMAGES_DIRS='${{ matrix.image }}/' ./build.sh
      - name: login to ghcr
        if: "github.ref == 'refs/heads/master'"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_WRITER }}
      - name: push images
        if: "github.ref == 'refs/heads/master'"
        run: MANUAL_IMAGES_DIRS='${{ matrix.image }}/' ./push.sh
  linters:
    name: check linters
    timeout-minutes: 11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: MegaLinter
        uses: oxsecurity/megalinter@v8
        env:
          VALIDATE_ALL_CODEBASE: true
